export const CONSTRUCTOR_INGREDIENT_ADD = "CONSTRUCTOR_INGREDIENT/ADD";
export const CONSTRUCTOR_INGREDIENT_DELETE = "CONSTRUCTOR_INGREDIENT/DELETE";
export const CONSTRUCTOR_INGREDIENT_REORDER = "CONSTRUCTOR_INGREDIENT/REORDER";
export const CONSTRUCTOR_INGREDIENTS_CLEAR = "CONSTRUCTOR_INGREDIENTS/CLEAR";
